name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: wrapper
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Generate test reports
      uses: dorny/test-reporter@v1
      if: success() || failure()
      continue-on-error: true
      with:
        name: Gradle Tests
        path: build/test-results/test/*.xml
        reporter: java-junit
        fail-on-error: false
        
    - name: Publish test results summary
      if: success() || failure()
      run: |
        echo "## 🧪 Test Results" >> $GITHUB_STEP_SUMMARY
        if [ -f build/test-results/test/TEST-*.xml ]; then
          TOTAL_TESTS=$(grep -o 'tests="[^"]*"' build/test-results/test/TEST-*.xml | cut -d'"' -f2 | paste -sd+ | bc)
          FAILED_TESTS=$(grep -o 'failures="[^"]*"' build/test-results/test/TEST-*.xml | cut -d'"' -f2 | paste -sd+ | bc)
          PASSED_TESTS=$((TOTAL_TESTS - FAILED_TESTS))
          echo "- ✅ Passed: $PASSED_TESTS" >> $GITHUB_STEP_SUMMARY
          echo "- ❌ Failed: $FAILED_TESTS" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 Total: $TOTAL_TESTS" >> $GITHUB_STEP_SUMMARY
        else
          echo "- 📝 No test results found" >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: Build plugin
      run: ./gradlew build
      
    - name: Verify plugin functionality
      run: |
        ./gradlew publishToMavenLocal
        cd test-plugin-project
        ../gradlew generateProtoKotlin
        ls -la build/generated/protokotlin/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-artifacts
        path: |
          build/libs/
          build/reports/
        retention-days: 7