name: Publish to Gradle Plugin Portal

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string
      dry-run:
        description: 'Dry run (validate only)'
        required: false
        default: false
        type: boolean

jobs:
  publish-plugin:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Set version
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        sed -i "s/version = \".*\"/version = \"$VERSION\"/" build.gradle.kts
        echo "Updated version to: $VERSION"
        
    - name: Run tests
      run: ./gradlew test
      
    - name: Validate plugin publication (dry run)
      if: ${{ github.event.inputs.dry-run == 'true' }}
      run: ./gradlew publishPlugins --validate-only
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        
    - name: Publish to Gradle Plugin Portal
      if: ${{ github.event.inputs.dry-run == 'false' }}
      run: ./gradlew publishPlugins
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        
    - name: Create success summary
      if: success()
      run: |
        if [ "${{ github.event.inputs.dry-run }}" == "true" ]; then
          echo "## ✅ Validation Successful" >> $GITHUB_STEP_SUMMARY
          echo "Plugin validation passed! Ready for publication." >> $GITHUB_STEP_SUMMARY
        else
          echo "## 🚀 Plugin Published Successfully" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** $VERSION" >> $GITHUB_STEP_SUMMARY
          echo "- **Plugin ID:** de.markusfluer.protokotlin.plugin" >> $GITHUB_STEP_SUMMARY
          echo "- **Portal URL:** https://plugins.gradle.org/plugin/de.markusfluer.protokotlin.plugin" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🎯 Users can now install with:" >> $GITHUB_STEP_SUMMARY
          echo '```kotlin' >> $GITHUB_STEP_SUMMARY
          echo 'plugins {' >> $GITHUB_STEP_SUMMARY
          echo '    id("de.markusfluer.protokotlin.plugin") version "'$VERSION'"' >> $GITHUB_STEP_SUMMARY
          echo '}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        fi